# Generated by Django 5.0.3 on 2024-03-27 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_paper_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(verbose_name='I am a Junior DevOps Engineer. I mainly dedicate my time to learn new techniques for managing and configuring widely used enterprice level applications such as Confluence, Bitbucket, Jira. I can create Data Centers in Cluster mode for each of these applications. In this blog, I will be sharing the application of installation, manangement, upgrading and configuring Linux and Windows servers for Bitbucket, Confluence, Jira and Jenkins and many more...')),
            ],
        ),
        migrations.CreateModel(
            name='Infos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infos', models.JSONField(verbose_name=({'github': {'link': 'https://github.com/kasimerbay'}, 'linkedin': {'link': 'https://www.linkedin.com/in/ahmetkasimerbay/'}, 'mail': {'link': 'devopsenginar@gmail.com'}, 'medium': {'link': 'https://medium.com/@ahmetkasim2'}},))),
            ],
        ),
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.JSONField(verbose_name={'name': 'Ahmet Kasım Erbay'})),
            ],
        ),
        migrations.CreateModel(
            name='Navs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navs', models.JSONField(verbose_name={'about': 'about', 'papers': 'papers'})),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateField(verbose_name='2024-03-27 15:03:18.032717')),
            ],
        ),
        migrations.RenameField(
            model_name='paper',
            old_name='content',
            new_name='post',
        ),
    ]
