# Generated by Django 5.0.3 on 2024-03-27 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_about_infos_name_navs_year_rename_content_paper_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
        migrations.DeleteModel(
            name='Infos',
        ),
        migrations.DeleteModel(
            name='Name',
        ),
        migrations.DeleteModel(
            name='Navs',
        ),
        migrations.DeleteModel(
            name='Year',
        ),
    ]
