# Generated by Django 5.0.3 on 2024-03-27 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_delete_about_delete_infos_delete_name_delete_navs_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paper',
            old_name='post',
            new_name='blog_post',
        ),
    ]
