# Generated by Django 5.0.3 on 2024-03-27 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_post_paper_blog_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Navs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
