# Generated by Django 5.0.3 on 2024-03-27 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_navs'),
    ]

    operations = [
        migrations.AddField(
            model_name='navs',
            name='nav_item',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
