# Generated by Django 5.0.3 on 2024-03-27 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_navs_nav_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navs',
            name='nav_item',
            field=models.CharField(db_index=True, default=None, max_length=10),
        ),
    ]
