# Generated by Django 5.0.3 on 2024-03-28 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_navs_nav_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('link', models.CharField(max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='navs',
            name='nav_item',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
