# Generated by Django 5.0.3 on 2024-03-28 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_contact_alter_navs_nav_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='url',
            field=models.URLField(default='#', max_length=50),
        ),
    ]
