# Generated by Django 5.0.3 on 2024-03-28 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_contact_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='url',
        ),
    ]
