# Generated by Django 5.0.3 on 2024-03-31 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_contact_id_alter_navs_id_alter_paper_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='blog_post',
        ),
        migrations.AddField(
            model_name='paper',
            name='post_link',
            field=models.URLField(default=None),
        ),
    ]
